worker_processes 1;
events { worker_connections 1024; }

http{
    include /etc/nginx/active/upstream.conf;

    server{
        listen 80;

    # API REST 6> backend Actif 
        location /api/ {
            proxy_pass http://back_active;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }


        location /healthz { return 200 'OK'; add_header Content-Type text/plain; }


        localtion / {
            proxy_pass http://front_active;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
         
    }
}